# Generated by Django 5.0.2 on 2024-03-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_create_film_actor_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
    ]
