# Generated by Django 5.0.2 on 2024-03-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Names',
            new_name='Name',
        ),
        migrations.RenameModel(
            old_name='Phones',
            new_name='Phone',
        ),
    ]
