# Generated by Django 5.0.2 on 2024-03-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_create_film_actor_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
